[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
python_files = test_*.py
addopts = -ra --strict-markers
filterwarnings =
    ignore:No directory at:UserWarning
    ignore:builtin type (swigvarlink|SwigPyPacked|SwigPyObject) has no __module__ attribute:DeprecationWarning
