# Generated by Django 5.2.17 on 2026-09-17 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('target_question_count', models.PositiveSmallIntegerField(default=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='workspace.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mcq', 'Multiple choice'), ('open', 'Open-ended')], max_length=8)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workspace.project')),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='materials.chunk')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.quizsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.FloatField()),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='workspace.project')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='assessment.question')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='assessment__project_4892d7_idx')],
            },
        ),
    ]
