# Generated by Django 5.2.17 on 2026-09-17 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('materials', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.3)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_misses', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='materials.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='workspace.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'concept'), name='uniq_mastery_project_concept')],
            },
        ),
        migrations.CreateModel(
            name='MasterySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot', to='assessment.attempt')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='materials.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='workspace.project')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'concept', 'created_at'], name='learning_ma_project_345d66_idx')],
            },
        ),
    ]
