# Generated by Django 5.2.17 on 2026-09-17 15:20

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('materials', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('goal', 'Goal'), ('preference', 'Preference'), ('strength', 'Strength'), ('weakness', 'Weakness'), ('repeated_mistake', 'Repeated Mistake'), ('note', 'Note')], max_length=32)),
                ('content', models.TextField()),
                ('salience', models.FloatField(default=0.5)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='materials.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='workspace.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'kind', 'created_at'], name='learning_le_project_2795e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('review_material', 'Review Material'), ('take_quiz', 'Take Quiz'), ('ask_tutor', 'Ask Tutor'), ('upload_material', 'Upload Material')], max_length=32)),
                ('text', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('superseded', 'Superseded')], default='active', max_length=16)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='materials.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='workspace.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status', 'created_at'], name='learning_re_project_8ca437_idx')],
            },
        ),
    ]
