# Generated by Django 5.2.17 on 2026-09-17 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite', models.CharField(db_index=True, max_length=64)),
                ('git_sha', models.CharField(blank=True, default='', max_length=40)),
                ('metrics', models.JSONField(default=dict)),
                ('case_results', models.JSONField(default=list)),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(db_index=True, max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('latency_ms', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error')], db_index=True, default='ok', max_length=8)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retries', models.IntegerField(default=0)),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to='workspace.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='ai_aicalllo_project_4588ac_idx'), models.Index(fields=['user', '-created_at'], name='ai_aicalllo_user_id_f6915b_idx')],
            },
        ),
    ]
