# Generated by Django 5.2.17 on 2026-09-17 12:10

import django.db.models.deletion
import materials.models
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField()),
                ('index', models.IntegerField()),
                ('text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='workspace.project')),
            ],
            options={
                'ordering': ['material_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='ChunkConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.chunk')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('importance', models.IntegerField(default=3)),
                ('chunks', models.ManyToManyField(related_name='concepts', through='materials.ChunkConcept', to='materials.chunk')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='workspace.project')),
            ],
            options={
                'ordering': ['-importance', 'name'],
            },
        ),
        migrations.AddField(
            model_name='chunkconcept',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.concept'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=materials.models.material_upload_path)),
                ('file_hash', models.CharField(max_length=64)),
                ('page_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workspace.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chunk',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='materials.material'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('project', 'normalized_name'), name='unique_concept_per_project'),
        ),
        migrations.AddConstraint(
            model_name='chunkconcept',
            constraint=models.UniqueConstraint(fields=('chunk', 'concept'), name='unique_chunk_concept'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('project', 'file_hash'), name='unique_file_per_project'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['project', 'material'], name='materials_c_project_6b80cc_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
